### Connect user
GET http://localhost:3000/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

### register user
POST http://localhost:3000/auths/login
Content-Type: application/json