@baseUrl = http://localhost:3000/scores


### get les scores du j1
GET {{baseUrl}}/player/1

### get les scores du t1
GET {{baseUrl}}/text/1

### get le score #1
GET {{baseUrl}}/1


### add un score j1 t1
POST {{baseUrl}}/add
Content-Type: application/json

{
    "player":1,
    "text":1,
    "score":150
}

### add un score j2 t1
POST {{baseUrl}}/add
Content-Type: application/json

{
    "player":2,
    "text":1,
    "score":230
}

### add un score j1 t2
POST {{baseUrl}}/add
Content-Type: application/json

{
    "player":1,
    "text":2,
    "score":240
}

### add un score j2 t2
POST {{baseUrl}}/add
Content-Type: application/json

{
    "player":2,
    "text":2,
    "score":190
}
