@baseUrl = http://localhost:3000/texts

### get all texts
GET {{baseUrl}}

### get one text
GET {{baseUrl}}/2

### add one text
POST {{baseUrl}}/add
Content-Type: application/json

{
    "title":"Nouvelle dictée",
    "text":"Apprécions ensemble cette nouvelle dictée: la dictée # >= 3"
}