@baseUrl = http://localhost:3000/users

### get le joueur 1
GET {{baseUrl}}/id/1

### get le joueur tartine
GET {{baseUrl}}/name/tartine

### envoi des scores à l'adresse de l'user connecté en 
### donnant le mot de passe de son adresse mail
POST {{baseUrl}}/sendScores
Content-Type: application/json

{
    "username":"zriphelo",
    "password":"2405DekSabSid1704"
}



### changer le nom d'un user
PUT {{baseUrl}}/tartine
Content-Type: application/json

{
    "password":"tartine",
    "username":"tartine",
    "role":"regular"
}

