@baseUrl = http://localhost:3000/users

###
GET {{baseUrl}}/id/1

###
GET {{baseUrl}}/name/tartine

###


### changer le nom d'un user
PUT {{baseUrl}}/tartine
Content-Type: application/json

{
    "password":"tartine",
    "username":"tartine",
    "role":"regular"
}

